appName: "D-S-Trace Archiver"

jMetricConfig:
  archivalEngineClass: "nitinka.jmetrics.archive.RRD4JArchivingEngine"
  configParams:
    basePath: "/var/log/dstrace-archiver/systemStats"

redisConsumerConfig:
  redisHost: "localhost"
  redisPort: 6379
  channels: ["tracer-event-channel"]

eventArchiveConfig:
  archiverClass: "nitinka.dstrace.archive.ElasticSearchEventArchiver"
  archiverConfig:
    elasticSearchHosts:
      - "localhost:9300"
    eventIndex: "trace"
  archiverThreads: 10

http:
  port: 9999
  adminPort: 9991
  rootPath: "/dstrace-archive/*"